### ISSUE TITLE
slider can not initialize successfully

### ISSUE THREAD

**Issue by fangjinyi** [dkazmer/sGlide#12]
if slider‘s parent’s ‘display’ attribute is ‘none’，then slider can not initialize successfully;
you may try this:

<div id="ssss" style="display: none;width: 200px;height: 20px;background:#1c94c4"><div id="silderss"></div></div>

<div id="btn" style="width: 100px;height: 200px;background:#c9302c">aaaa</div>

```
   $(document).ready(function(){
       $("#silderss").sGlide({
           height       : 10,
           width       :80,
           unit        :'%',
           image        : 'img/knob_.png',
           startAt      : 70,
           colorShift   : ['#3a4d31', '#7bb560'],
           buttons      : true
       });
       $("#btn").click(function(){
           $("#ssss").css("display","block");
       })
   });
```

**Comment by dkazmer** [comment]
I'd wager that it does initialize successfully, but may display as hidden or distorted because it relies on the parent's dimensions. Instead of "display:none" try visibility or opacity styles.

Daniel Kazmer
http://webshifted.com
Date: Sat, 23 Jan 2016 21:12:02 -0800
