### ISSUE TITLE
a.indexOf error with new version of Jquery

### ISSUE THREAD

**Issue by kabeda** [dkazmer/sGlide#13]
Hi,
I've started to use sGlide and with jQuery v3.2.1 I've got this error "**TypeError: a.indexOf is not a function**", I've changed this line in Image handling  (about 282) 

`knob.children('img').load(function(){`

with

`knob.children('img').on('load',function(){`

and it works (until now).

**Comment by kabeda** [comment]
Hi,
Finally, I have to forget this script. Not responsive.

**Comment by dkazmer** [comment]
Hi. Can you elaborate on your last comment please?

**Comment by kabeda** [comment]
Hi, just try with your examples on a full width windows then change the size of this window to as small as possible. You'll see that the slider becomes "mad". It gives wrong values.

**Comment by dkazmer** [comment]
Hi. This issue has been addressed in recently-released v3.
