### ISSUE TITLE
How to get slider value in call back ?

### ISSUE THREAD

**Issue by hkbeer** [dkazmer/sGlide#14]
First thank you for this great tool you have created.
I am trying to get the slider value from call back.
This is code I am trying to get but cannot get it. Please help how should I modify it, thanks

```
$('.slider_bar').sGlide({
'drop': function (o) {
  alert(o.value);
 },
etc
```

**Comment by dkazmer** [comment]
You're welcome. Please see [official website](http://webshifted.com/sGlide/) for code samples.
Tip: try console-logging `o` to see what's inside. The `value` prop doesn't exist anymore.
