### ISSUE TITLE
clicking on the bar (not the knob) gives incorrect value

### ISSUE THREAD

**Issue by chatziko** [dkazmer/sGlide#6]
Trying the example1 at http://iframework.net/sGlide/, when I click in the middle of the bar (not on the knob), I get 0% instead of 50%. Only sliding the knob works.

Tested on Firefox 35 and Chrome 40.

**Comment by dkazmer** [comment]
Thanks for the feedback. I believe version 2.1.1 takes care of this issue. Value now updates on mouse up.
