### ISSUE TITLE
Not working for versions below Android 4.4.x

### ISSUE THREAD

**Issue by ESTSky** [dkazmer/sGlide#8]
Hi,

I tried to use sGlide for mobile development. It works fine for Android 4.4.x only. When I deployed to earlier Android versions, it just shows a black screen and do not display the slider at all.

**Comment by ESTSky** [comment]
To narrow down the scenario, the issue is just happening in non-jquery version of SGlide. In other words, JQuery-SGlide is working fine.

**Comment by dkazmer** [comment]
Hi. Thanks for the feedback. I always appreciate it. Unfortunately I don't have an Android device on which to test, and this is such a fringe case that I'm okay with it being unresolved for the time being. However, if you or someone you know might like to take a crack at it, have at it. :+1: 
Thanks!

**Comment by dkazmer** [comment]
Made some improvements to v3, which may address this issue...
