### ISSUE TITLE
Snap to 10%

### ISSUE THREAD

**Issue by radem205** [dkazmer/sGlide#9]
Hi,

Thanks for all your effort in bringing up such a nice slider! 

Is it possible to snap the knob to every 10%? The setting marker with a max of 9 results in steps of 12.5%. Is there a reason why the numbers of snap points are limited to 9?

Thanks for your reply!

**Comment by dkazmer** [comment]
Just saw this. Initially 9 seemed like a nice number at which to stop as it prevents users from cluttering the bar with too many snap points, and I just didn't want to enter double digit integers. I suppose I shouldn't worry about the former, but I may still cap it anyway, and the latter just seems arbitrary now. I'll probably revise. Thanks.

**Comment by dkazmer** [comment]
v3 addresses this issue. I upped the maximum snap points to 11. Thanks for suggesting.
